<?php

namespace Database\Seeders;

use App\Models\Provider;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\URL;

class ProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $urlPath = url()->current();

        $providersData = [
            [
                "name" => "Ростелеком",
                "phone" => "8-903-940-09-90",
                "tech_support_phone" => "8-800-100-08-00",
                "rating_overall" => 3.45,
                "rating_connection" => 3.56,
                "rating_stability" => 3.56,
                "rating_speed" => 3.33,
                "rating_service" => 3.33,
                "description" => "Мобильная связь, интернет, роутер, сим-карта, Мобильная связь",
                "order" => 1,
                "image" => "$urlPath/storage/images/2024/rostelecom.png",
                "plans_count" => 4,
                "promotions_count" => 1,
                "reviews_count" => 6,
                "min_price" => 200,
                "min_internet_speed_value" => 100,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 1,
                "max_internet_speed_units" => "Гбит/с",
                "card_bg_color" => "#b429db",
            ],
            [
                "name" => "МТС",
                "phone" => "8-903-940-09-90",
                "tech_support_phone" => "8-800-250-08-90",
                "rating_overall" => 3.06,
                "rating_connection" => 3.22,
                "rating_stability" => 2.78,
                "rating_speed" => 3.33,
                "rating_service" => 2.89,
                "description" => "домашний интернет, мобильная связь, спутниковый интернет, ТВ",
                "order" => 6,
                "image" => "$urlPath/storage/images/2024/mts.png",
                "plans_count" => 5,
                "promotions_count" => 0,
                "reviews_count" => 2,
                "min_price" => 308,
                "min_internet_speed_value" => 100,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 5,
                "max_internet_speed_units" => "Гбит/с",
                "card_bg_color" => "#ff0032",
            ],
            [
                "name" => "ДОМ.РУ",
                "phone" => "89039400990",
                "tech_support_phone" => "88002507777",
                "rating_overall" => 2.86,
                "rating_connection" => 3.22,
                "rating_stability" => 2.89,
                "rating_speed" => 2.89,
                "rating_service" => 2.44,
                "description" => "Выгодный интернет, услуги, мобильная связь,",
                "order" => 7,
                "image" => "$urlPath/storage/images/2024/domru.png",
                "plans_count" => 4,
                "promotions_count" => 1,
                "reviews_count" => 2,
                "min_price" => 340,
                "min_internet_speed_value" => 125,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 800,
                "max_internet_speed_units" => "Мбит/с",
                "card_bg_color" => "#f6422b",
            ],
            [
                "name" => "ТТК",
                "phone" => "89039400990",
                "tech_support_phone" => "88007750775",
                "rating_overall" => 2.75,
                "rating_connection" => 3,
                "rating_stability" => 2.89,
                "rating_speed" => 2.67,
                "rating_service" => 2.44,
                "description" => "ТВ+Мобила",
                "order" => 8,
                "image" => "$urlPath/storage/images/2024/ttk.png",
                "plans_count" => 9,
                "promotions_count" => 5,
                "reviews_count" => 1,
                "min_price" => 150,
                "min_internet_speed_value" => 80,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 500,
                "max_internet_speed_units" => "Мбит/с",
                "card_bg_color" => "#e21a1a",
            ],
            [
                "name" => "Теле2",
                "phone" => "89039400990",
                "tech_support_phone" => "89049900000",
                "rating_overall" => 3,
                "rating_connection" => 3,
                "rating_stability" => 3.11,
                "rating_speed" => 2.89,
                "rating_service" => 3,
                "description" => "надежный тариф надежный тариф надежныйтарифнадежныйтарифнадежныйтарифнадежныйтарифнадежныйтарифнадежныйтарифнадежныйтарифнадежныйтарифнадежныйтар",
                "order" => 10,
                "image" => "$urlPath/storage/images/2024/tele2.png",
                "plans_count" => 5,
                "promotions_count" => 3,
                "reviews_count" => 3,
                "min_price" => 99,
                "min_internet_speed_value" => 100,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 500,
                "max_internet_speed_units" => "Мбит/с",
                "card_bg_color" => "#141414",
            ],
            [
                "name" => "Билайн",
                "phone" => "89039400990",
                "tech_support_phone" => "88007008000",
                "rating_overall" => 3.06,
                "rating_connection" => 2.11,
                "rating_stability" => 3.67,
                "rating_speed" => 3.22,
                "rating_service" => 3.22,
                "description" => "домашний интернет, видеонаблюдение, спутниковый ТВ",
                "order" => 11,
                "image" => "$urlPath/storage/images/2024/beeline.png",
                "plans_count" => 5,
                "promotions_count" => 1,
                "reviews_count" => 3,
                "min_price" => 1500,
                "min_internet_speed_value" => 100,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 1,
                "max_internet_speed_units" => "Гбит/с",
                "card_bg_color" => "#eec21d",
            ],
            [
                "name" => "Сибирские сети",
                "phone" => "89039400990",
                "tech_support_phone" => "83833055217",
                "rating_overall" => 3,
                "rating_connection" => 3.22,
                "rating_stability" => 2.78,
                "rating_speed" => 2.22,
                "rating_service" => 3.78,
                "description" => "безлимитный интернет, безлимитный интернет, безлимитный интернет",
                "order" => 55,
                "image" => "$urlPath/storage/images/2024/sibset.png",
                "plans_count" => 1,
                "promotions_count" => 0,
                "reviews_count" => 2,
                "min_price" => 150,
                "min_internet_speed_value" => 220,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 221,
                "max_internet_speed_units" => "Мбит/с",
                "card_bg_color" => "#0d5cf0",
            ],
            [
                "name" => "Мегафон",
                "phone" => "89039400990",
                "tech_support_phone" => "88005500500",
                "rating_overall" => 2.61,
                "rating_connection" => 2.56,
                "rating_stability" => 1.56,
                "rating_speed" => 3.33,
                "rating_service" => 3,
                "description" => "ТВ",
                "order" => 74,
                "image" => "$urlPath/storage/images/2024/megafon.png",
                "plans_count" => 6,
                "promotions_count" => 1,
                "reviews_count" => 1,
                "min_price" => 100,
                "min_internet_speed_value" => 100,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 1,
                "max_internet_speed_units" => "Гбит/с",
                "card_bg_color" => "#02b956",
            ],
            [
                "name" => "Электронный город",
                "phone" => "89039400990",
                "tech_support_phone" => "88007753750",
                "rating_overall" => 2.94,
                "rating_connection" => 3.11,
                "rating_stability" => 2.44,
                "rating_speed" => 3.22,
                "rating_service" => 3,
                "description" => "спутниковое тв, Спутниковое тв, Спутниковое Тв, Спутниковое тв, Спутниковое тв, Спутниковое тв, Спутниковое тв, Спутниковое тв, Спутниковое тв",
                "order" => 75,
                "image" => "$urlPath/storage/images/2024/electrongorod.png",
                "plans_count" => 0,
                "promotions_count" => 0,
                "reviews_count" => 3,
                "min_price" => 307,
                "min_internet_speed_value" => 800,
                "min_internet_speed_units" => "Мбит/с",
                "max_internet_speed_value" => 1,
                "max_internet_speed_units" => "Гбит/с",
                "card_bg_color" => "#fe403c",
            ],
        ];

        foreach ($providersData as $data) {
            Provider::firstOrCreate($data);
        }
    }
}
